version: "3"
services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    ports:
      - "8011:80"
    volumes:
      - ./:/var/www/html
      - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    volumes:
      - ./mysql/data:/var/lib/mysql
