version: "3"
services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    ports:
      - "8011:80"
    volumes:
      - ./:/var/www/html
      - ./apache/default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=poke3000
      - MYSQL_USER=poke
      - MYSQL_PASSWORD=poke3000
    volumes:
      - ./mysql/data:/var/lib/mysql
